# .streamlit/secrets.toml
[connections.my_snowflake_connection]
account = "JP45674"
user = "mohamedgaber98"
password = "QV45-QYsH!Gi7x3"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
role = "SYSADMIN"
